Fix CI

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -33,10 +33,10 @@ jobs:
       - name: Install dependencies
         if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
         run: poetry install --no-interaction --no-root
-      - name: Stop Docker Compose services
-        run: docker-compose down
       - name: Run tests
         run: cd ${{ github.workspace }} && run.sh
+      - name: Stop Docker Compose services || echo "Failed to graceful shutdown, ignored"
+        run: docker-compose down
     # container: python:3.9.15
     # services:
     #   postgres:
